In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [9]:
d = load_iris()
# d

In [12]:
x = pd.DataFrame(d.data, columns=d.feature_names)
y = d.target
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y)
model = LogisticRegression()
model.fit(x_train, y_train)
pr_tr = model.predict(x_train)
pr_te = model.predict(x_test)
accuracy_score(y_train, pr_tr), accuracy_score(y_test, pr_te)

(0.9821428571428571, 0.9736842105263158)

In [48]:
k = 5
count = 150 // k
scores_tr = []
scores_te = []
ind = np.linspace(0, 149, 150, dtype='int16')
np.random.shuffle(ind)

for i in range(k):
    te_ind = ind[count * i : count * (i + 1)]
    tr_ind = np.concatenate([ind[:count * i], ind[count * (i + 1):]]) 

    if isinstance(x, pd.DataFrame):
        x_train = x.values[tr_ind]
        x_test = x.values[te_ind]
    else:
        x_train = x[tr_ind]
        x_test = x[te_ind]

    y_train = y[tr_ind]
    y_test = y[te_ind]

    model = LogisticRegression()
    model.fit(x_train, y_train)
    pr_tr = model.predict(x_train)
    pr_te = model.predict(x_test)
    scores_tr.append(accuracy_score(y_train, pr_tr))
    scores_te.append(accuracy_score(y_test, pr_te))

scores_tr = np.array(scores_tr)
scores_te = np.array(scores_te)

print(scores_tr)
print(scores_te)

scores_tr.mean(), scores_te.mean()

[0.975      0.96666667 0.975      0.975      0.99166667]
[0.96666667 0.96666667 0.96666667 0.96666667 0.93333333]


C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


(0.9766666666666666, 0.96)